"""add days to hire stats table

Revision ID: 224c5fc049d9
Revises: 991ecb2bf269
Create Date: 2025-05-15 22:32:06.363152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224c5fc049d9'
down_revision = '991ecb2bf269'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days_to_hire_stats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('standard_job_id', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('avg_days_to_hire', sa.Integer(), nullable=False),
    sa.Column('min_days_to_hire', sa.Integer(), nullable=False),
    sa.Column('max_days_to_hire', sa.Integer(), nullable=False),
    sa.Column('job_posting_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('days_to_hire_stats', schema='public')
    # ### end Alembic commands ###
